### ISSUE TITLE
Fix random crash?

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#104]
I've gotten this crash now twice, i dont know what triggers it but ive seen it on heavymovement and dungeonslice now with different talents.

link: https://github.com/simulationcraft/simc/runs/1201982778

```
Run cd tests
1..1
not ok 1 Class talent test
# (from function `talent_sim' in file test_helper.bash, line 32,
#  in test file talents.bats, line 4)
#   `talent_sim ${SIMC_CLASS}' failed with status 134
# Error in sim: /home/runner/work/simc/b/ninja/simc /home/runner/work/simc/simc/profiles/Tier25/T25_Priest_Shadow.simc iterations=2 threads=2 fight_style=HeavyMovement output=/dev/null cleanup_threads=1 talents=0000300 default_actions=1
# === Output begins here ===
# SimulationCraft 901-01 for World of Warcraft 9.0.2.36086 shadowlands-BETA (hotfix 2020-10-02/36086, git build shadowlands 320445d)
# 
# simc: ../../simc/engine/action/sc_action.cpp:93: virtual void (anonymous namespace)::queued_action_execute_event_t::execute(): Assertion `action->cooldown->ready <= sim().current_time()' failed.
# === Output ends here ===
Error: Process completed with exit code 1.
```

If I re-run the jobs it fixes it, and I cannot reproduce this locally at all.

@scamille any ideas?

**Comment by scamille** [comment]
I can take a look at it. Test runs with only 2 iterations so if you have a rare crash condition it might not always crash that quickly, and that's why you are only seeing this sporadically.

So I am not really surprised, thanks for pointing it out. The idea with the tests running a much larger combination space is exactly to catch things which are normally not summer that often.

This ticket would probably have been better opened in the SimC project.

**Comment by seanpeters86** [comment]
should be fixed by https://github.com/simulationcraft/simc/commit/15b9334a7aeafa2b61915aa59d0516e2d988cbcc
