### ISSUE TITLE
Preliminary Research for new DungeonSlice sims

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#149]
DungeonSlice is an approximation for dungeon environments, but doesn't quite hit the mark on what we are looking for. Is there a way we could take the same idea and maybe tweak it to get it to the next level? The current block is defined [here](https://github.com/simulationcraft/simc/blob/shadowlands/engine/sim/sc_sim.cpp#L2317-L2334):

```cpp
    max_time                       = timespan_t::from_seconds( 360.0 );
    //Disables all raidbuffs, except those provided by scrolls or the character itself.
    optimal_raid                   = 0;
    overrides.arcane_intellect     = 1;
    overrides.battle_shout         = 1;
    overrides.power_word_fortitude = 1;
    overrides.bloodlust            = 1;

    ignore_invulnerable_targets = true;

    raid_events_str +=
        "/invulnerable,cooldown=500,duration=500,retarget=1"
        "/adds,name=Boss,count=1,cooldown=500,duration=135,type=add_boss,duration_stddev=1"
        "/adds,name=SmallAdd,count=5,count_range=1,first=140,cooldown=45,duration=15,duration_stddev=2"
        "/adds,name=BigAdd,count=2,count_range=1,first=160,cooldown=50,duration=30,duration_stddev=2";
```

Which produces something like this level of target uptime:

| Targets | Percentage|
| --- | --- |
| 1 | 54% |
| 2 | 16% |
| 3 | 9% |
| 4 | 3% |
| 5 | 6% |
| 6 | 6% |
| 7 | 7% |

So what I'm thinking is that we kind of expand on this a bit to get a better "composite" sim for dungeon slice. Something like different options for:
- Tyranical vs. Fortified
- Maybe add in Prideful buff uptime?
- Trash heavy dungeon (plaguefall) vs. Boss heavy dungeon (mists)

**Comment by Saeldur** [comment]
I'm not sure if building a single dungeon approximation is the correct move and definitely think that composite styled is the best.
We'll definitely want Trash Heavy, Boss Heavy and mixed with something like 25%25%/50% weighting respectively.
We'll probably want some pulls based roughly off what happens. Such as funnel styled pulls with small adds and some medium/big adds, pure aoe pulls and then small 3-4 mob pulls.
I'd consider the "boss heavy" slice to be made primarily of 3-4 mob pulls, prideful st encounters and boss encounters.
"Mixed" Slice to be have one or two 6-8 mob pulls, primarily 3-4 mob pulls, prideful st encounters and boss encounters
"Trash Heavy" to be 3-4 6-8 mob pulls, 1-2 3-4 mob pulls, prideful st encounters and boss encounters.
"Trash heavy" might also have 3 pridefuls before trash pulls, 2 large 1 normal and the rest before bosses.
"Boss heavy" might have 3 pridefuls before bosses, rest before trash.
"Mixed" should be a fairly equal split.

Do we potentially also want to support "Key scaling" which basically has Low keys (+10 approximation) where mobs live for very short times, Average(?) (+15 approximation) and High (+20 Approximation)?

**Comment by seanpeters86** [comment]
> Do we potentially also want to support "Key scaling" which basically has Low keys (+10 approximation) where mobs live for very short times, Average(?) (+15 approximation) and High (+20 Approximation)?

That's a really good question, I think a good target for us would be whatever the weekly box caps at (I think is 14/15 now?) As that what will be most relevant for people. Going below/above that might not be worth our time

**Comment by ItsLowbo** [comment]
Interested in looking into this - really dislike simming patchwerk multi target for dungeons and want to find something better.

Here's a version I've been messing around with today -

8 Minute Patchwerk Single Target sim, plus:

raid_events+=/invulnerable,cooldown=500,duration=500,retarget=1
raid_events+=/adds,name=Boss,count=1,cooldown=500,duration=120,type=add_boss,last=10
raid_events+=/adds,name=TrashPack,count=4,count_range=2,first=130,last=310,cooldown=50,duration=40
raid_events+=/adds,name=MiniBoss,count=1,first=330,type=add_boss,cooldown=500,duration=60
raid_events+=/adds,name=PostMiniBossTrash,count=4,count_range=2,first=400,cooldown=50,duration=40,last=470


Logic is instead of directly trying to sim one dungeon, instead generate a variety of situations and prefer a build that can deal with all of them well. This is supposed to represent roughly 1/4 of a +15 mythic keystone dungeon, with a boss, trash packs of various sizes, and a Tormented miniboss with 10 second breaks in between.

The fight durations and time between fights are mostly guesses, and obviously would be very different in Tyrannical and Fortified, but I wanted to get some feedback and a sanity check on the general direction before I take it any further.

**Comment by ItsLowbo** [comment]
Is it possible to use variables for raid event times? Ideally the standard deviations for fight durations would be much larger, but I couldn’t find a way to say “spawn the next pack X seconds after the previous one went down”


Also, is it possible to make the "main boss" completely untargetable? I've noticed running various classes through this sim that, for example, Frost Mage will cast Blizzard with one attackable target to reset Frozen Orb faster. That will definitely throw off the sim.
