### ISSUE TITLE
Remove insanity from Shadow Word: Death

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#15]
ACs:
- [x] Shadow Word: Death no longer generates insanity baseline
- [x] remove Gain from `priest()`

**Comment by lgkern** [comment]
I removed the generation baseline, but it still generates from the legendary. It didn't have a gain right now.

**Comment by scamille** [comment]
simulationcraft/simc@aeac0c5af3cd4d018708b5ec1319a5d997d8f523 removed the gain from the action, and I had removed the priest gain before.

All actions have default gain objects, which are used for any normal action which consumes mana or other resources. 
In the past, priests did not use that because of complications, but it does make a lot of things special in that it uses a special system instead of what is in the SimC core.

So I removed the custom priest gain objects where the automated systems would just take care of all this. You can always check in the html report if a resource gain/loss is there or not.
