### ISSUE TITLE
Include a description in each chart

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#185]
Right now the charts just include a single button about the sim, but it doesn't describe in detail what that sim actually is. Need to think of a way to pass through or code a description into each one of these charts.

Could embed a description into the `config.yml` and pass this into the JSON response for the chart, or something else entirely. This will likely be a multi-sentence description mimicking what is in the `README.md` for each folder.

Thoughts?

**Comment by lutzmor** [comment]
Hey,
for the frontend it doesn't matter if you pass the description in the config.yml or the actual json. The only thing which could get a bit problemetic if you add a second file like "Results_Composite_am_kyrian_description.md" because then i need to first read that file remember it in a variable then read the json and then "combine" them.
The easy way would be add it to the config.yml in the following way:

`sims:
    conduits:
      description: Some quite complex description for what we did in this sim and some very useful things
      builds: true
      ......`

With this i can use the config to show it on the page, because the config.yml got read at first and is available after that
everywhere in the code. So we have a minimal change on the side of the script and the frontend only need to read it
from the config. I only need to change some stuff with the header so that the end result on the page looks something like this:

`HEADER
 DESCRIPTION
 CHART`

or if i only show the description without any change to the charts it will look like this:

`DESCRIPTION
 HEADER
CHART`

**Comment by seanpeters86** [comment]
Okay I just pushed in some descriptions to the config if that helps. Let me know if you want this passed to the results json at any point

**Comment by lutzmor** [comment]
Thx Publik i opened a pr for this ( https://github.com/WarcraftPriests/WarcraftPriests.github.io/pull/25 ).
