### ISSUE TITLE
APL Testing

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#50]
As we get closer to launch we can start doing more testing around parts of the APL. This is not an exhaustive list, just a good place to start

ACs:
- [ ] hold void bolt out of voidform with HV to line up with cds if coming soon
- [ ] Use Unholy Nova before Void Eruption on AoE? Probably not worth for Single Target but with Lead by Example the burst could be useful
- [ ] delay VoiT in non-opener for PI
- [ ] voidform sync/optimization with niya's grove invigoration
- [x] check if any shadowlands trinkets should have custom conditions
- [ ] vampiric touch target cap
- [ ] racial sims
- [ ] Shadow Crash optimization + target cap?
- [ ] Mind Blast APL with Mind Devourer
- [ ] Boon of the Ascended with Hungering Void/single target in general + dungeonslice
- [ ] check if we should delay certain CDs with hungering void talented
- [x] Dissonant echoes is a dps loss, probably due to void bolting out of voidform being weird value wise (gets worse at higher ranks)
- [ ] Dark Thoughts Overflow in Voidform (tried to fix with [this commit](https://github.com/simulationcraft/simc/commit/9e9614f652d07ef60c6754b9ee8213e01f335339))
- [x] Check PI + Voidform sync
  - [x] delay voidform for PI (current implementation)
  - [x] delaying PI for Voidform
  - [ ] don't delay at all (test with a higher base sim duration)
  - [ ] if the fight timings change this, we should support several fight durations
- [x] `raid_event.movement` optimizations (i.e. void torrent)
- [x] Potion usage
- [x] Dungeon Slice optimization
- [x] Fae Guardians (DungeonSlice is particularly bad)
- [x] S2M + Mindbender + Legendary APL for DungeonSlice
- [x] target cap on mindgames (when not taking theotars final ability)
- [x] delay mindgames for voidform with theotar?
- [x] SW:D with Painbreaker Psalm
- [x] target cap on Void Torrent
- [x] Searing Nightmare target cutoff
- [x] Arcane Torrent usage while moving
- [x] Adjust Mind Blast usage if using Talbadar's
- [x] check SW:D on the move vs. SW:P
- [x] target cap on Mind Blast (current TODO in the apl)
- [x] prepull action
- [x] check if we want a dots check on mindbender for opener
- [x] target cap on SW:D
- [x] target cap on DP without SN
- [x] Voidform and Power Infusion CD sync
- [x] Mindbender/Shadowfiend
- [x] Void Torrent
- [x] Unholy Nova DungeonSlice
- [x] Actor casts SW:P to make sure wrathful is applied after casting Fae Guardians
- [x] Void Bolt target cutoff

**Comment by seanpeters86** [comment]
Saeldur found a nice increase for void torrent here: https://github.com/simulationcraft/simc/compare/77124ad8e8b9...05d509074389

```
# Composite
| Actor | DPS | Increase |
|---|:---:|:---:|
|Desync_VoiT_and_Voidform_Buff|2765|0.87%|
|Base|2742|0.00%|
```

```
# Dungeons
| Actor | DPS | Increase |
|---|:---:|:---:|
|Desync_VoiT_and_Voidform_Buff|2674|1.21%|
|Base|2642|0.00%|
```

```
# Single
| Actor | DPS | Increase |
|---|:---:|:---:|
|Desync_VoiT_and_Voidform_Buff|2505|0.94%|
|Base|2482|0.00%|
```

**Comment by seanpeters86** [comment]
@jaervified found this increase for dungeonslice searing nightmare: https://github.com/simulationcraft/simc/commit/4720a86fd56654ca9c76d8cc195c75595fee43f7

```
# Dungeons
| Actor | DPS | Increase |
|---|:---:|:---:|
|Move_VT_Higher_Priority|2634|2.41%|
|Base|2572|0.00%|
```

**Comment by seanpeters86** [comment]
Racial Bonuses to check:
- [x] nightborne - not worth, basically everything i tried was a dps loss
- [x] lightforged draenei - added some more conditions for adds
- [x] troll - sync with power infusion
- [x] blood elf - arcane torrent still sucks, only using in precombat
- [x] dark iron dwarf - was already using with Voidform up, swapped to PI to be more consistent
- [x] maghar orc - syncing with PI
- [x] vul'pera - disabling, this is terrible

**Comment by seanpeters86** [comment]
# Void Bolt Testing

## Hungering Void (`talents=1121122`)

### Composite
| Actor | DPS | Increase |
|---|:---:|:---:|
|extra_vb_line|9689|1.56%|
|move_vb|9681|1.48%|
|extra_vb_line_st_only|9597|0.59%|
|Base|9541|0.00%|

### Dungeons
| Actor | DPS | Increase |
|---|:---:|:---:|
|extra_vb_line|8590|0.67%|
|extra_vb_line_st_only|8577|0.52%|
|move_vb|8572|0.46%|
|Base|8533|0.00%|

### Single Target
| Actor | DPS | Increase |
|---|:---:|:---:|
|move_vb|8840|1.15%|
|extra_vb_line_st_only|8837|1.12%|
|extra_vb_line|8837|1.11%|
|Base|8740|0.00%|

## Ancient Madness (`talents=1121121`)

### Composite
| Actor | DPS | Increase |
|---|:---:|:---:|
|extra_vb_line|9123|0.04%|
|extra_vb_line_st_only|9122|0.03%|
|Base|9120|0.00%|
|move_vb|9119|-0.01%|

### Dungeons
| Actor | DPS | Increase |
|---|:---:|:---:|
|Base|8454|0.00%|
|extra_vb_line_st_only|8454|0.00%|
|move_vb|8453|-0.01%|
|extra_vb_line|8445|-0.11%|

### Single Target
| Actor | DPS | Increase |
|---|:---:|:---:|
|extra_vb_line|8362|0.07%|
|move_vb|8362|0.07%|
|extra_vb_line_st_only|8362|0.06%|
|Base|8357|0.00%|

**Comment by Saeldur** [comment]
Need to confirm:

- [ ] Check PI + Voidform sync for non-fae/Kyrian covenants again, specifically for Shadowflame Prism. Initial investigations show holding voidform for power infusion as necrolord is a dps boost. Check on multiple fight lengths. Specifically, delay voidform for PI, which is no longer the current implementation. The default currently is power infusion currently gets held for the last use of voidform, not voidform holding for pi.
- [ ] Check to see if Dreamweaver Fae Optimisations are worth considering
- [ ] Check if Venthyr Nadjia Euphoria windows are worth playing around and if so to what extent. Especially with the 9.1 capstone buffed version.
- [ ] Fae Covenant Legendary
- [ ] Necrolord Covenant Legendary
- [ ] Venthyr Covenant Legendary
- [ ] Kyrian Covenant Legendary
- [ ] Boon of the ascended Kyrian Shadowflame - Treat Pelagos as a mastery buff and ignore ascended blast except for filler potentially? Or other optimisations like Late Boon to get through the initial insanity deluge and to get priority spells on cooldown before entering boon rotation, similar to how ordnance kyrian currently plays.
- [ ] Check if pooling dark thoughts shortly before a Shadowflame Prism mindbender is worth losing mindblast uses, and if so how much of a mindblast is allowed to be lost? E.g. how many GCDs can mindblast sit off CD.
- [ ] Check if Adjusting SWD in execute to be Shadowflame Mindbender aware is a dps increase. Check on multiple fight lengths. Short execute is likely not worth the consideration vs extended execute.
- [ ] Check if we should sacrifice voidbolts on Single Target, potentially aoe, if insanity is flooding but hungering void debuff is still up. This is specifically for extremely high haste sims (>100% in cds, especially >147% with single GCD. Sacrificing Single GCD spacing for two GCD at 147% was a dps increase during some testing for Paladin Blessing of Autumn) or for 9.1 Fae SFP with RS7+ where you flood on ST. It is potentially worth losing fractional voidbolts in order to avoid overcapping tens of insanity across the voidform.
- [ ] Check if Mind Devourer causes insanity floods in voidform, if it does check it as part of the investigation for voidbolt mentioned above.
- [ ] Adjust non Fae CD usage for Voidform and SFP Mindbender to hold for the last power infusion / dps potion / VF if they will occur in the sim. Use the cooldown at the last possible point in the fight where it will still get value and will overlap the additional CD that it is being held for. If the CD will get the full value delay for that CD entirely. This includes necrolord covenant ability.
- [ ] Revisit Vampiric Touch Target Cap to properly find a concise point at which it should stop applying them
- [ ] Recheck Dot Time To Die for SWP and VT. SWP is considerably weaker than the old version I expect it needs considerably higher TTD than previous use cases. The same for Vampiric Touch.
- [ ] Consider splitting the APL into raid event (Adds, specifically) aware and non raid event aware. This is to simplify the APL drastically where CD timing optimizations are causing issues in hectic add cleave or dungeon slice. Use CDs around raid events more than other CDs in that. 
- [ ] Consider splitting the APL to have different action lists for target counts if it makes it easier to rewrite the apl - I find this less likely to be useful than the above change though.
- [ ] Create a True Voidform CD remaining variable to use instead of checking voidforms current cooldown to avoid issues with Fae Guardians cooldown reduction. This should factor in the expected cooldown reduction from currently active fae guardians. Potentially consider another variable to include potential future uses of Fae Guardians before voidform comes up. This is linked to the comment below.
- [ ] Change logic on cooldown management to be based off the expected time of next use. This will factor its cooldown AND other ability cooldowns. This is to manage cases where abilities are being held for a cooldown coming up but that cooldown is being delayed until another. This is similar to currently how voidforms APL works but make see if its possible to make it understand the time until the condition is satisfied, roughly.
