### ISSUE TITLE
Look over APL for SN/Mind Sear/VT cutoff

### ISSUE THREAD

**Issue by jaervified** [WarcraftPriests/sl-shadow-priest#72]
```
actions.main+=/mind_sear,target_if=spell_targets.mind_sear>variable.mind_sear_cutoff&buff.dark_thoughts.up,chain=1,interrupt_immediate=1,interrupt_if=ticks>=2
```

Is causing issues with the SN APL where it might overprioritize sear in situations where we are trying to find cutoffs for DT and VT.
Investigate later...

// Jaerv

**Comment by seanpeters86** [comment]
This is because of the location of this line in the APL + the location/condition of mind blast

Basically it is casting mind sear because it has a Dark Thought Proc it is trying to spend, but it never spends it because the mind blast condition isnt created/made for this to work properly.

So we need to do some testing:
- [ ] add a line to consume dark thoughts procs with mind blast up to a certain target count (i.e. do we stop using these procs at 4 targets? 6?
- [ ] after finding that mark add a condition to the existing mind blast line (or maybe a new one above searing nightmare in priority) to consume the proc at this cutoff
- [ ] adjust the mind sear line listed above to only cast mind sear for this specific condition if that target count is met. So if we say only use dark thought procs with mind sear at or below X targets, this line shouldnt cast mind sear if you are at X+1 targets

**Comment by seanpeters86** [comment]
@jaervified we can start this work again now that searing nightmare is fixed
