### ISSUE TITLE
Charts are missing talent sims

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#78]
There is no talents sims on the charts

**Comment by lutzmor** [comment]
This is related to the config.yml in this repo, there the build parameter is set to false and the page goes over the items under sims and only add the ones to the page where "build: true" is set.

Will take a look at that, and see what's "possible" ;). Even if you remove the check for true there are problems. Because the site expects a different layout of the result then the repo has :).

**Comment by lutzmor** [comment]
A "fix" is in the pull request here ( https://github.com/WarcraftPriests/WarcraftPriests.github.io/pull/4 )

**Comment by lutzmor** [comment]
can be closed done with merged pull request  https://github.com/WarcraftPriests/WarcraftPriests.github.io/pull/5
