### ISSUE TITLE
Void Torrent no longer refreshes Devouring Plague

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/sl-shadow-priest#87]
requires https://github.com/WarcraftPriests/sl-shadow-priest/issues/80

Remove refresh when casting Void Torrent for Devouring Plague, and instead trigger a fresh Devouring Plague on cast, but not continually refresh it.

TODO:
- [x] what happens if you cast this with Devouring Plague already active?
- [x] do you get initial hit damage from devouring plague?
- [x] does this proc Mind Devourer?
- [x] does this proc a Shadowy Apparition?

ACs:
- [x] Void Torrent change to add a DP trigger on execute only
- [x] Figure out APL wise if you should only cast VoiT with DP already active or not

**Comment by jaervified** [comment]
what happens if you cast this with Devouring Plague already active?
It behaves like you just casted 1 DP manually, ignites like normal and refreshes to base duration.
https://www.warcraftlogs.com/reports/PZ9KVyzdRFQm7w1G/#fight=last&type=damage-done&source=1&view=events&ability=335467

do you get initial hit damage from devouring plague?
Yes
00:00:08.609 --> https://www.warcraftlogs.com/reports/PZ9KVyzdRFQm7w1G/#fight=last&type=damage-done&source=1&view=events

does this proc Mind Devourer?
No

https://www.warcraftlogs.com/reports/PZ9KVyzdRFQm7w1G/#fight=last&type=casts&source=1&pins=0%24Separate%24%23244F4B%24auras-gained%240%240.0.0.Any%240.0.0.Any%24true%241206288.0.0.Priest%24false%24338333&ability=263165

does this proc a Shadowy Apparition?
No

https://www.warcraftlogs.com/reports/MG6n1VLFAP7avrp3/#fight=last&type=casts&source=14&view=events
